name: Create Version Bump PR

# on:
#   pull_request:
#     types: [closed]
#     branches:
#       - main

on:
  pull_request:
    branches:
    - main


permissions:
  contents: write # for checkout and tag
  pull-requests: write # for comments

jobs:
  create-version-bump-pr:
    # if: github.event.pull_request.merged == true
    name: Create Version Bump PR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm ci

    - name: Get PR labels
      id: pr-labels
      uses: actions/github-script@v6
      with:
        script: |
          const { data: pullRequest } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });
          
          const labels = pullRequest.labels.map(label => label.name);
          const validLabels = ['major', 'minor', 'patch', 'premajor', 'preminor', 'prepatch', 'prerelease'];
          const versionLabel = labels.find(label => validLabels.includes(label));
          return versionLabel;

    - name: Bump version and create branch
      run: |
        if [[ "${{ steps.pr-labels.outputs.result }}" != "" ]]; then
            # Bump version without creating a git tag or commit
            NEW_VERSION=$(npm version ${{ steps.pr-labels.outputs.result }} --no-git-tag-version)
            branch_name="${{ steps.pr-labels.outputs.result }}-${NEW_VERSION}"
            
            git checkout -b $branch_name
            git commit -am "chore: version bump to ${NEW_VERSION}"
            git push origin HEAD:$branch_name
        fi

    - name: Create PR for version bump
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "${{ steps.pr-labels.outputs.result }}-${NEW_VERSION}"
        destination_branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Version Bump"
        pr_body: "Automated version bump based on merged PR labels. Please review."
