name: release:ci

on:
  pull_request:
    branches:
    - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Configure
        run: |
          npm config set @codefi:registry ${NPM_PRIVATE_REGISTRY_URL}
          npm config set ${NPM_PRIVATE_REGISTRY_URL#http*:}:_authToken $NPM_PRIVATE_REGISTRY_TOKEN
        env:
          NPM_PRIVATE_REGISTRY_URL: ${{ secrets.NPM_PRIVATE_REGISTRY_URL }}    
      - name: Configure 2
        run: npm config set ${NPM_PRIVATE_REGISTRY_URL#http*:}:_authToken $NPM_PRIVATE_REGISTRY_TOKEN
        env:
          NPM_PRIVATE_REGISTRY_URL: ${{ secrets.NPM_PRIVATE_REGISTRY_URL }}
          NPM_PRIVATE_REGISTRY_TOKEN: ${{ secrets.NPM_PRIVATE_REGISTRY_TOKEN }}
      - name: Publish
        run: npm publish